version: '3.8'

services:
  app:
    container_name: my_app

    build:
      context: .
      dockerfile: docker/app/Dockerfile

    restart: always

    env_file:
      - .env

    ports:
      - ${APP_PORT}:8000

    depends_on:
      - db
      - storage

  db:
    container_name: my_postgres
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always
    env_file:
      - .env

  storage:
    container_name: my_redis

    build:
      context: .
      dockerfile: docker/redis/Dockerfile

    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    ports:
      - ${REDIS_PORT}:6379

    volumes:
      - .redis:/data

    restart: always

    command: [redis-server, /usr/local/etc/redis.conf]

    env_file:
      - .env
