version: '3.8'

services:
  app:
    container_name: my_app
    build: ./
    depends_on:
      - db
      - storage
    ports:
      - ${APP_PORT}:8000
    restart: always
    env_file:
      - .env

  db:
    container_name: my_postgres
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always
    networks:
      - postgres
    env_file:
      - .env

  storage:
    container_name: my_redis
    image: redis:alpine
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - .redis:/data
      - ./redis.conf:/usr/local/etc/redis.conf
    restart: always
    command: [redis-server, /usr/local/etc/redis.conf]
    env_file:
      - .env

  pgadmin:
    container_name: my_pgadmin
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
    env_file:
      - .env

networks:
  postgres:
    driver: bridge
