version: '3.8'

services:
  app:
    container_name: my_app

    build:
      context: .
      dockerfile: docker/app/Dockerfile

    restart: always

    env_file:
      - .env

    ports:
      - ${APP_PORT}:8000

    depends_on:
      - db
      - storage

  db:
    container_name: my_postgres
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always
    env_file:
      - .env

  storage:
    container_name: my_redis

    build:
      context: .
      dockerfile: docker/redis/Dockerfile
      args:
        - password = ${REDIS_PASSWORD}

    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    ports:
      - ${REDIS_PORT}:6379

    volumes:
      - .redis:/data

#    command:
#      - "mkdir -p /usr/local/etc/redis"
#      - 'echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf'
#      - 'echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf'
#      - "redis-server /usr/local/etc/redis/redis.conf"
#      - "redis-cli -a $REDIS_PASSWORD set messages []"

    restart: always

    env_file:
      - .env
